### NumPy: Функции & Модули [Домашнее задание]
> **
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Пожалуйста, протестируйте все функции, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [2]:
import numpy as np

In [4]:
# numpy.zeros
print(np.zeros((2,2,2)))

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [5]:
# numpy.ones
print(np.ones((2,2,2)))

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


In [13]:
# numpy.full
print(np.full((2,2,2), 1234))

[[[1234 1234]
  [1234 1234]]

 [[1234 1234]
  [1234 1234]]]


In [30]:
# numpy.eye
print(np.eye(3))
print(np.eye(10))
print(np.eye(10,5, k = 2))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [26]:
# numpy.arange
print(np.arange(0.5,100,1.5))

[ 0.5  2.   3.5  5.   6.5  8.   9.5 11.  12.5 14.  15.5 17.  18.5 20.
 21.5 23.  24.5 26.  27.5 29.  30.5 32.  33.5 35.  36.5 38.  39.5 41.
 42.5 44.  45.5 47.  48.5 50.  51.5 53.  54.5 56.  57.5 59.  60.5 62.
 63.5 65.  66.5 68.  69.5 71.  72.5 74.  75.5 77.  78.5 80.  81.5 83.
 84.5 86.  87.5 89.  90.5 92.  93.5 95.  96.5 98.  99.5]


In [32]:
# numpy.add
arr1 = np.array([1,2,3])
arr2= np.array([4,5,6])
print(np.add(arr1,arr2))

[5 7 9]


In [33]:
# numpy.subtract
print(np.subtract(arr1,arr2))

[-3 -3 -3]


In [35]:
# numpy.sin
print(np.sin(arr1))

[0.84147098 0.90929743 0.14112001]


In [37]:
# numpy.multiply
print(np.multiply(arr1,arr2))

[ 4 10 18]


In [38]:
# numpy.sqrt
print(np.sqrt(arr1))

[1.         1.41421356 1.73205081]


In [44]:
# numpy.dot
arr2 = np.array([[1],[2],[4]])
arr1 = np.array([10,12,14])
print(np.dot(arr1,arr2))

[[1]
 [2]
 [4]]
[10 12 14]
[90]


In [46]:
# numpy.sum
print(np.sum(arr1))

36


In [48]:
# numpy.zeros_like
np.zeros_like(arr2)

array([[0],
       [0],
       [0]])

In [56]:
# numpy.empty_like
np.empty_like(arr1)

array([508044688,       431,         0])

In [62]:
# numpy.reshape
a = np.array([[1,2,3],[4,5,6]])
print(a)
a =np.reshape(a,(3,2))
print(a)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [65]:
# numpy.isnan
a = np.array([np.nan,123,123,123,np.nan,np.nan])
print(np.isnan(a))

[ True False False False  True  True]


2. Пожалуйста, протестируйте все функции модуля ```numpy.random```, упомянутые в видео лекции, и постарайтесь разобраться в них. 
Некоторые функции содержат аргументы, пожалуйста, поэкспериментируйте с ними.

In [3]:
import numpy.random as rd 

In [4]:
# numpy.random.sample
print(rd.sample((2,2)))

[[0.31664955 0.62232114]
 [0.81494437 0.93162905]]


In [5]:
# numpy.random.random
print(rd.random((2,2)))

[[0.53243981 0.68186458]
 [0.38299734 0.73034296]]


In [7]:
# numpy.random.randint
print(rd.randint(0,2,(2,2)))

[[1 1]
 [0 1]]


In [81]:
# numpy.random.random_integers
print(rd.random_integers(1,2,(4,4)))

[[1 2 1 2]
 [1 2 2 1]
 [1 2 1 2]
 [2 1 2 2]]


<ipython-input-81-520f6235cbe1>:2: DeprecationWarning: This function is deprecated. Please call randint(1, 2 + 1) instead
  print(rd.random_integers(1,2,(4,4)))


In [82]:
# numpy.random.uniform
rd.uniform((2,2))

array([1.2114597 , 1.65738664])

In [127]:
# numpy.random.seed
rd.seed(10) #0.771

In [128]:
print(rd.random())

0.771320643266746


In [116]:
rd.seed(1) #0.417

In [117]:
print(rd.random())

0.417022004702574


In [132]:
# numpy.random.shuffle
a = ['a','b','c','d','e']
print(a)
rd.shuffle(a)
print(a)

['a', 'b', 'c', 'd', 'e']
['d', 'c', 'e', 'b', 'a']


In [134]:
a = [1,1,5,6,3,4,]
print(a)
rd.shuffle(a)
print(a)

[1, 1, 5, 6, 3, 4]
[1, 3, 5, 4, 1, 6]


In [139]:
a = np.array([1,1,5,6,3,4,])
print(a)
rd.shuffle(a)
print(a)


[1 1 5 6 3 4]
[1 5 3 6 1 4]


In [145]:
# numpy.random.permutation
print(rd.permutation(10))
print(rd.permutation([1,1,5,6,3,4,]))
a = np.arange(9).reshape((3,3))
print(rd.permutation(a))

[6 2 3 4 7 9 5 8 0 1]
[4 1 3 6 5 1]
[[3 4 5]
 [0 1 2]
 [6 7 8]]


In [11]:
# numpy.random.choice
print(np.random.choice(5,50))
print(np.random.choice(2, 4))

[1 0 0 3 4 2 2 0 4 2 2 2 1 3 4 3 3 4 3 0 4 4 2 3 4 0 2 3 3 0 3 2 4 3 2 0 1
 4 2 4 1 3 2 0 1 1 1 3 2 4]
[0 1 1 0]


# Прекрасная работа!