### NumPy: Введение (Часть 2) [Домашнее задание]

> **Пожалуйста, избегайте использования одномерных массивов numpy.ndarray.**
> **Пишите код только там, где это показано для записи. Не удаляйте комментарии!**

1. Импортируйте пакет NumPy

In [31]:
# Начало вашего кода
import numpy as np
# Конец вашего кода
print(np.__version__)

1.20.1


### Ожидаемый результат
```
1.17.4
```

2. Создайте двумерный numpy.ndarray **numbers**, где первая строка содержит четные числа от 0 до 10, а вторая строка содержит нечетные числа от 0 до 10 (10 не учитывается в обоих случаях).

In [32]:
# Начало вашего кода
num_list = [[0,2,4,6,8,] , [1,3,5,7,9]] 
numbers = np.array(num_list)
# Конец вашего кода
print(numbers)

[[0 2 4 6 8]
 [1 3 5 7 9]]


### Ожидаемый результат
```
[[0 2 4 6 8]
 [1 3 5 7 9]]
```

3. Пожалуйста, проверьте все важные атрибуты (упомянутые в видео-лекции) для numpy.ndarray even_np и распечатайте их.

In [3]:
# Начало вашего кода
print(numbers.ndim)
print(numbers.shape)
print(numbers.size)
print(numbers.dtype)
print(numbers.T)
# Конец вашего кода

2
(2, 5)
10
int32
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


### Ожидаемый результат
```
2
(2, 5)
10
int64
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
```

4. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray.

In [33]:
# Начало вашего кода
overall_max = numbers.max()
overall_min = numbers.min()
overall_mean = numbers.mean()
overall_std = numbers.std()
# Конец вашего кода
print(overall_max)
print(overall_min)
print(overall_mean)
print(overall_std)

9
0
4.5
2.8722813232690143


### Ожидаемый результат
```
9
0
4.5
2.8722813232690143
```

5. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждого **столбца**.

In [8]:
# Начало вашего кода
col_max = numbers.max(axis = 0, keepdims = True)
col_min = numbers.min(axis = 0, keepdims = True)
col_mean = numbers.mean(axis = 0, keepdims = True)
col_std = numbers.std(axis = 0, keepdims = True)
# Конец вашего кода
print(col_max)
print(col_min)
print(col_mean)
print(col_std)

[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]


### Ожидаемый результат
```
[[1 3 5 7 9]]
[[0 2 4 6 8]]
[[0.5 2.5 4.5 6.5 8.5]]
[[0.5 0.5 0.5 0.5 0.5]]
```

6. Найдите максимальное, минимальное, среднее, стандартное отклонение, используя методы numpy.ndarray для каждой **строки**.

In [34]:
# Начало вашего кода
row_max = numbers.max(axis = 1, keepdims = True)
row_min = numbers.min(axis = 1, keepdims = True)
row_mean = numbers.mean(axis = 1, keepdims = True)
row_std = numbers.std(axis = 1, keepdims = True)
# Конец вашего кода
print(row_max)
print(row_min)
print(row_mean)
print(row_std)

[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]


### Ожидаемый результат
```
[[8]
 [9]]
[[0]
 [1]]
[[4.]
 [5.]]
[[2.82842712]
 [2.82842712]]
```

7. Создайте объект numpy.ndarray из списка list_of_lists, приведенного ниже. Кроме того, рассчитать среднее значение и стандартное отклонение по всем осям.

In [35]:
list_of_lists = [[[1,2],[3,4]],[[21,22],[23,24]]]
# Начало вашего кода
thd_nparr = np.array(list_of_lists)
# Конец вашего кода
print(thd_nparr)

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


### Ожидаемый результат
```
[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]
```

In [36]:
# Начало вашего кода
print('Mean with respect to 0-axis')
print(thd_nparr.mean(axis = 0 , keepdims = True))
print('STD with respect to 0-axis')
print(thd_nparr.std(axis = 0 , keepdims = True))
print('Mean with respect to 1-axis')
print(thd_nparr.mean(axis = 1 , keepdims = True))
print('STD with respect to 1-axis')
print(thd_nparr.std(axis = 1 , keepdims = True))
print('Mean with respect to 2-axis')
print(thd_nparr.mean(axis = 2 , keepdims = True))
print('STD with respect to 2-axis')
print(thd_nparr.std(axis = 2 , keepdims = True))

# Конец вашего кода

Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]
Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]
Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]


### Ожидаемый результат
```
Mean with respect to 0-axis
[[[11. 12.]
  [13. 14.]]]
STD with respect to 0-axis
[[[10. 10.]
  [10. 10.]]]


Mean with respect to 1-axis
[[[ 2.  3.]]

 [[22. 23.]]]
STD with respect to 1-axis
[[[1. 1.]]

 [[1. 1.]]]


Mean with respect to 2-axis
[[[ 1.5]
  [ 3.5]]

 [[21.5]
  [23.5]]]
STD with respect to 2-axis
[[[0.5]
  [0.5]]

 [[0.5]
  [0.5]]]
```

8. Пожалуйста, предоставьте применение следующих методов numpy.ndarray ниже:

In [37]:
# ndarray.reshape()
# Начало вашего кода
thd_nparr.reshape(1,4,2)
# Конец вашего кода

array([[[ 1,  2],
        [ 3,  4],
        [21, 22],
        [23, 24]]])

In [38]:
# ndarray.ravel()
# Начало вашего кода
thd_nparr.ravel()
# Конец вашего кода

array([ 1,  2,  3,  4, 21, 22, 23, 24])

In [39]:
# ndarray.tolist()
# Начало вашего кода
thd_nparr.tolist()
# Конец вашего кода

[[[1, 2], [3, 4]], [[21, 22], [23, 24]]]

In [40]:
# ndarray.tofile()
# Начало вашего кода
thd_nparr.tofile('text.txt', sep = ',')
# Конец вашего кода

In [72]:
# ndarray.sort()
# Начало вашего кода
thd_nparr.sort()
print(thd_nparr)
# Конец вашего кода

[[[ 1  2]
  [ 3  4]]

 [[21 22]
  [23 24]]]


In [73]:
# ndarray.transpose()
# Начало вашего кода
thd_nparr.transpose()
# Конец вашего кода

array([[[ 1, 21],
        [ 3, 23]],

       [[ 2, 22],
        [ 4, 24]]])

In [74]:
# ndarray.flatten()
# Начало вашего кода
thd_nparr.flatten()
# Конец вашего кода

array([ 1,  2,  3,  4, 21, 22, 23, 24])

In [75]:
# ndarray.argmin()
# Начало вашего кода
thd_nparr.argmin()
# Конец вашего кода

0

In [76]:
# ndarray.argmax()
# Начало вашего кода
thd_nparr.argmax()
# Конец вашего кода

7

In [77]:
# ndarray.cumsum()
# Начало вашего кода
thd_nparr.cumsum()
# Конец вашего кода

array([  1,   3,   6,  10,  31,  53,  76, 100], dtype=int32)

In [41]:
# ndarray.cumprod()
# Начало вашего кода
thd_nparr.cumprod()
# Конец вашего кода

array([      1,       2,       6,      24,     504,   11088,  255024,
       6120576], dtype=int32)

In [42]:
# ndarray.dot()
# Начало вашего кода
thd_nparr.dot([[1,2],[3,4]])
# Конец вашего кода

array([[[  7,  10],
        [ 15,  22]],

       [[ 87, 130],
        [ 95, 142]]])

In [80]:
# ndarray.squeeze()
# Начало вашего кода
a = [[[2, 2, 2], [2, 2, 2]]]
arr = np.array(a)
print(arr)
print(arr.squeeze())
# Конец вашего кода

[[[2 2 2]
  [2 2 2]]]
[[2 2 2]
 [2 2 2]]


In [81]:
# ndarray.repeat()
# Начало вашего кода
print(thd_nparr.repeat(1))
print(thd_nparr.repeat(2))
print(thd_nparr.repeat(3))
# Конец вашего кода

[ 1  2  3  4 21 22 23 24]
[ 1  1  2  2  3  3  4  4 21 21 22 22 23 23 24 24]
[ 1  1  1  2  2  2  3  3  3  4  4  4 21 21 21 22 22 22 23 23 23 24 24 24]


# Прекрасная работа!