### Категорийные данные [Домашнее задание]

**Примечание:**

> Пожалуйста, не удаляйте комментарии или строки кода.

1. Пожалуйста, импортируйте необходимые библиотеки, и загрузите набор данных ```"titanic"``` из библиотеки ```seaborn```.

In [1]:
# Начало кода
import seaborn as sns 
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

data = sns.load_dataset('titanic')
data.head()
# Конец кода

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

2. Пожалуйста, реализуйте функцию ```label_encoding(labels)```, которая будет возвращать закодированные категорийные данные на основе ```Label Encoding```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [7]:
df = data['sex'][data["sex"].values=='male'].copy()
df

Series([], Name: sex, dtype: object)

In [ ]:
def label_encoding(labels):
    # Начало кода
    data = pd.Series(labels)
    data = 
    # Конец кода
    return (encoded, label2idx, idx2label)

encoded, label2idx, idx2label = label_encoding(data["sex"].values)
print(encoded[:10])
print(label2idx)
print(idx2label)

### Ожидаемые результаты:

```python
[0, 1, 1, 1, 0, 0, 0, 0, 1, 1]
{'male': 0, 'female': 1}
{0: 'male', 1: 'female'}
```

3. Пожалуйста, реализуйте функцию ```onehot_encoding(labels)```, которая будет возвращать закодированные категорийные данные на основе ```One-hot Encoding```. Вы не можете использовать библиотеку ```sklearn``` в этой задаче.

In [ ]:
def onehot_encoding(labels):
    # Начало кода

    # Конец кода
    return (encodings, label2idx, idx2label)

encodings, label2idx, idx2label = onehot_encoding(data["sex"].values)
print(encodings)
print(label2idx)
print(idx2label)

### Ожидаемые результаты:

```python
[[1. 0.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [1. 0.]
 [1. 0.]]
{'male': 0, 'female': 1}
{0: 'male', 1: 'female'}
```

4. Пожалуйста, реализуйте функцию ```label_encoding_sklearn(labels)```, которая будет возвращать закодированные категорийные данные на основе ```Label Encoding```. Вы должны использовать библиотеку ```sklearn``` в этой задаче.

In [ ]:
def label_encoding_sklearn(labels):
    # Начало кода

    # Конец кода
    return (encoded, encoder)

encoded, encoder = label_encoding_sklearn(data["sex"].values.reshape(-1,1))
print(encoded[:10])
print(encoder)

### Ожидаемые результаты:

```python
[1 0 0 0 1 1 1 1 0 0]
LabelEncoder()
```

5. Пожалуйста, реализуйте функцию ```onehot_encoding_sklearn(labels)```, которая будет возвращать закодированные категорийные данные на основе ```One-hot Encoding```. Вы должны использовать библиотеку ```sklearn``` в этой задаче.

In [ ]:
def onehot_encoding_sklearn(labels):
    # Начало кода

    # Конец кода
    return (encoded, encoder)
encoded, encoder = onehot_encoding_sklearn(data["sex"].values.reshape(-1,1))
print(encoded)
print(encoder)

### Ожидаемые результаты:

```python
[[0. 1.]
 [1. 0.]
 [1. 0.]
 ...
 [1. 0.]
 [0. 1.]
 [0. 1.]]
OneHotEncoder()
```

6. Пожалуйста, реализуйте функцию ```hash_encoding_sklearn(labels)```, которая будет возвращать закодированные категорийные данные на основе ```Hashing```. Вы должны использовать библиотеку ```sklearn``` в этой задаче.

In [ ]:
def hash_encoding_sklearn(labels, n_features=4, input_type="string"):
    # Начало кода

    # Конец кода
    return (encoded, encoder)
encoded, encoder = hash_encoding_sklearn(data["sex"].values.reshape(-1,1))
print(encoded)
print(encoder)

### Ожидаемые результаты:

```python
[[-1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0. -1.  0.  0.]
 ...
 [ 0. -1.  0.  0.]
 [-1.  0.  0.  0.]
 [-1.  0.  0.  0.]]
FeatureHasher(input_type='string', n_features=4)
```

7. Теперь попробуйте использовать эти реализованные функции и преобразовать другие категориальные столбцы в ```data``` в закодированные данные.

In [ ]:
# Начало кода

# Конец кода

### Отличная работа